# Auto-generated by pylunix_icon_gen - Do not edit manually

from PyQt5.QtGui import QIcon, QPixmap, QColor, QPainter
from PyQt5.QtSvg import QSvgRenderer
from PyQt5.QtCore import QSize, Qt

from . import resources_win_rc

class IconAccessor(str):
    def __call__(self, color: str = None, size: QSize = QSize(16,16)) -> QIcon:
        if color is None or not self.lower().endswith('.svg'):
            return QIcon(self)
        renderer = QSvgRenderer(self)
        pixmap = QPixmap(size)
        pixmap.fill(Qt.transparent)
        painter = QPainter(pixmap)
        renderer.render(painter)
        painter.setCompositionMode(QPainter.CompositionMode_SourceIn)
        painter.fillRect(pixmap.rect(), QColor(color))
        painter.end()
        return QIcon(pixmap)

class ThemeIconMeta(type):
    def __new__(mcs, name, bases, attrs):
        new_attrs = {}
        for key, value in attrs.items():
            if isinstance(value, str) and value.startswith(':/'):
                new_attrs[key] = IconAccessor(value)
            else:
                new_attrs[key] = value
        return super().__new__(mcs, name, bases, new_attrs)

class WinIcon(metaclass=ThemeIconMeta):
    """Auto-generated icons for the 'win' theme. Generated by pylunix_icon_gen."""
    CHECKMARK = IconAccessor(':win/CheckMark.svg')
    CHEVRONDOWN = IconAccessor(':win/ChevronDown.svg')
    CHEVRONUP = IconAccessor(':win/ChevronUp.svg')
    CLEAR = IconAccessor(':win/Clear.svg')
    SEARCH = IconAccessor(':win/Search.svg')